### ISSUE TITLE
Response Headers Never Get Parsed

### ISSUE THREAD

**Issue by kencbarrett** [raml-org/raml-dotnet-parser-2#14]
Hello,

I ran into an issue where response headers were never parsed in the `ResponsesBuilder` class.  It seems that the data type of the value of the response headers dictionary is not the same as that of the value property of the request headers dictionary.  Specifically, the data type of the value property of the response headers dictionary is `System.Object[]` not  `System.Dynamic.ExpandoObject` like the request headers dictionary.  So, when this is cast to `IDictionary<string, object>` it is always null, which results in `dynamicRaml` always being null in `ParametersBuilder`.  Subsequently, response headers are never parsed.

I believe the real issue is in the underlying JavaScript parser.  Ideally, it should return the same data types for the value of the request headers dictionary and the response headers dictionary.  That way, when they are cast to `IDictionary<string, object>` and passed into the `ParametersBuilder` constructor, it works correctly for both.

As a workaround, I just converted the response headers dictionary to what is expected:

```c#
private IDictionary<string, object> GetHeaders(IDictionary<string, object> response)
{
    if (!response.ContainsKey("headers"))
    {
        return null;
    }
    
    dynamic hdrs = response["headers"];
    var headers = new Dictionary<string, object>();
     
    foreach (var header in hdrs)
    {
         headers.Add(header.name, header);
    }

    return headers;
 }
```
Then, passed that in to the constructor to ParametersBuilder instead of casting `values["headers"] as IDictionary<string, object>` since it will always be null:

```c#
IDictionary<string, object> headers = GetHeaders(value);

list.Add(new Response
{
    Code = pair.Key,
    Description = value.ContainsKey("description") ? value["description"] as string : null,
    Body = GetBody(defaultMediaType, value),
    Headers = headers != null
                        ? new ParametersBuilder(headers).GetAsDictionary()
                        : new Dictionary<string, Parameter>(),
   Annotations = AnnotationsBuilder.GetAnnotations(value)
});
```

This worked for me, and the headers for my responses are now getting parsed and populated correctly.

**Comment by woodp** [comment]
Thanks for the feedback. I will check it, similar issues emerged after upgrading the js parser.
