### ISSUE TITLE
Adding nuget package to vs2015 project stalls studio and blows .prj file size up to 1.5MB

### ISSUE THREAD

**Issue by CameronAM** [raml-org/raml-dotnet-parser-2#20]
Adding the nuget package of a vs2015 project is not a great experience, it:-

1. Stalls visual studio for minutes during the add operation (with no feedback or warning)
2. Increases the size of the project file dramatically

It appears to be unnecessarily adding thousands of files from the node_modules directory into the vs project, this causes studio to slow down and stall during simple operations, eg. starting debugging.

Can I safely exclude the node_modules from the vs project? 

Can the nuget package be updated so that it does not add these files whenever the package is updated?

**Comment by woodp** [comment]
The package uses a javascript parser underneath, those node_modules are necessary.
